CREATE TABLE user_logs (
id SERIAL PRIMARY KEY ,
user_id INT NOT NULL ,
name VARCHAR(150) NOT NULL ,
page VARCHAR(255) NOT NULL ,
age  INT NOT NULL ,
duration INT ,
join_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP ,
metadata JSONB
);
